name: ${project.name}
main: name.richardson.james.bukkit.starterkit.StarterKit
author: grandwazir
description: Give items to new players.
website: https://grandwazir.github.com/StarterKit
version: ${project.version}
commands:
  sk:
    description: 'StarterKit root command'
    alias: [starterkit]
    usage: '/sk'
permissions:
  starterkit:
    description: Allow players to use all the features of StarterKit.
    children:
      starterkit.list: true
      starterkit.load: true
      starterkit.save: true
  starterkit.list:
    description: Allow players to list what is in the StarterKit
  starterkit.load:
    description: Allow players to get a copy of the kit.
    children:
      starterkit.load.self: true
      starterkit.load.others: true
  starterkit.load.self:
    description: Allow players to give themselves a StarterKit manually.
  starterkit.load.others:
    description: Allow players to give other players StarterKits manually.
  starterkit.save:
    description: Allow players to save a new kit.
